spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ticket-server
            uri: lb://ticket-server
            predicates:
              - Path=/api/v1/ticket/**
          - id: user-server
            uri: lb://user-server
            predicates:
              - Path=/api/v1/user/**
          - id: vehicle-service
            uri: lb://vehicle-service
            predicates:
              - Path=/api/v1/vehicle/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payment/**
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
